# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexandre/projects/c/ga

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexandre/projects/c/ga

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexandre/projects/c/ga/CMakeFiles /home/alexandre/projects/c/ga//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexandre/projects/c/ga/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named genetic

# Build rule for target.
genetic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 genetic
.PHONY : genetic

# fast build rule for target.
genetic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genetic.dir/build.make CMakeFiles/genetic.dir/build
.PHONY : genetic/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named helpers

# Build rule for target.
helpers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 helpers
.PHONY : helpers

# fast build rule for target.
helpers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helpers.dir/build.make CMakeFiles/helpers.dir/build
.PHONY : helpers/fast

#=============================================================================
# Target rules for targets named ga.out

# Build rule for target.
ga.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ga.out
.PHONY : ga.out

# fast build rule for target.
ga.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ga.out.dir/build.make CMakeFiles/ga.out.dir/build
.PHONY : ga.out/fast

game/body_part.o: game/body_part.cpp.o
.PHONY : game/body_part.o

# target to build an object file
game/body_part.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/body_part.cpp.o
.PHONY : game/body_part.cpp.o

game/body_part.i: game/body_part.cpp.i
.PHONY : game/body_part.i

# target to preprocess a source file
game/body_part.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/body_part.cpp.i
.PHONY : game/body_part.cpp.i

game/body_part.s: game/body_part.cpp.s
.PHONY : game/body_part.s

# target to generate assembly for a file
game/body_part.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/body_part.cpp.s
.PHONY : game/body_part.cpp.s

game/food.o: game/food.cpp.o
.PHONY : game/food.o

# target to build an object file
game/food.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/food.cpp.o
.PHONY : game/food.cpp.o

game/food.i: game/food.cpp.i
.PHONY : game/food.i

# target to preprocess a source file
game/food.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/food.cpp.i
.PHONY : game/food.cpp.i

game/food.s: game/food.cpp.s
.PHONY : game/food.s

# target to generate assembly for a file
game/food.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/food.cpp.s
.PHONY : game/food.cpp.s

game/gui.o: game/gui.cpp.o
.PHONY : game/gui.o

# target to build an object file
game/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/gui.cpp.o
.PHONY : game/gui.cpp.o

game/gui.i: game/gui.cpp.i
.PHONY : game/gui.i

# target to preprocess a source file
game/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/gui.cpp.i
.PHONY : game/gui.cpp.i

game/gui.s: game/gui.cpp.s
.PHONY : game/gui.s

# target to generate assembly for a file
game/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/gui.cpp.s
.PHONY : game/gui.cpp.s

game/player.o: game/player.cpp.o
.PHONY : game/player.o

# target to build an object file
game/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/player.cpp.o
.PHONY : game/player.cpp.o

game/player.i: game/player.cpp.i
.PHONY : game/player.i

# target to preprocess a source file
game/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/player.cpp.i
.PHONY : game/player.cpp.i

game/player.s: game/player.cpp.s
.PHONY : game/player.s

# target to generate assembly for a file
game/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/player.cpp.s
.PHONY : game/player.cpp.s

genetic/chromosome.o: genetic/chromosome.cpp.o
.PHONY : genetic/chromosome.o

# target to build an object file
genetic/chromosome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genetic.dir/build.make CMakeFiles/genetic.dir/genetic/chromosome.cpp.o
.PHONY : genetic/chromosome.cpp.o

genetic/chromosome.i: genetic/chromosome.cpp.i
.PHONY : genetic/chromosome.i

# target to preprocess a source file
genetic/chromosome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genetic.dir/build.make CMakeFiles/genetic.dir/genetic/chromosome.cpp.i
.PHONY : genetic/chromosome.cpp.i

genetic/chromosome.s: genetic/chromosome.cpp.s
.PHONY : genetic/chromosome.s

# target to generate assembly for a file
genetic/chromosome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genetic.dir/build.make CMakeFiles/genetic.dir/genetic/chromosome.cpp.s
.PHONY : genetic/chromosome.cpp.s

genetic/gene.o: genetic/gene.cpp.o
.PHONY : genetic/gene.o

# target to build an object file
genetic/gene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genetic.dir/build.make CMakeFiles/genetic.dir/genetic/gene.cpp.o
.PHONY : genetic/gene.cpp.o

genetic/gene.i: genetic/gene.cpp.i
.PHONY : genetic/gene.i

# target to preprocess a source file
genetic/gene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genetic.dir/build.make CMakeFiles/genetic.dir/genetic/gene.cpp.i
.PHONY : genetic/gene.cpp.i

genetic/gene.s: genetic/gene.cpp.s
.PHONY : genetic/gene.s

# target to generate assembly for a file
genetic/gene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genetic.dir/build.make CMakeFiles/genetic.dir/genetic/gene.cpp.s
.PHONY : genetic/gene.cpp.s

genetic/population.o: genetic/population.cpp.o
.PHONY : genetic/population.o

# target to build an object file
genetic/population.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genetic.dir/build.make CMakeFiles/genetic.dir/genetic/population.cpp.o
.PHONY : genetic/population.cpp.o

genetic/population.i: genetic/population.cpp.i
.PHONY : genetic/population.i

# target to preprocess a source file
genetic/population.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genetic.dir/build.make CMakeFiles/genetic.dir/genetic/population.cpp.i
.PHONY : genetic/population.cpp.i

genetic/population.s: genetic/population.cpp.s
.PHONY : genetic/population.s

# target to generate assembly for a file
genetic/population.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/genetic.dir/build.make CMakeFiles/genetic.dir/genetic/population.cpp.s
.PHONY : genetic/population.cpp.s

helpers/utils.o: helpers/utils.cpp.o
.PHONY : helpers/utils.o

# target to build an object file
helpers/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helpers.dir/build.make CMakeFiles/helpers.dir/helpers/utils.cpp.o
.PHONY : helpers/utils.cpp.o

helpers/utils.i: helpers/utils.cpp.i
.PHONY : helpers/utils.i

# target to preprocess a source file
helpers/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helpers.dir/build.make CMakeFiles/helpers.dir/helpers/utils.cpp.i
.PHONY : helpers/utils.cpp.i

helpers/utils.s: helpers/utils.cpp.s
.PHONY : helpers/utils.s

# target to generate assembly for a file
helpers/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helpers.dir/build.make CMakeFiles/helpers.dir/helpers/utils.cpp.s
.PHONY : helpers/utils.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ga.out.dir/build.make CMakeFiles/ga.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ga.out.dir/build.make CMakeFiles/ga.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ga.out.dir/build.make CMakeFiles/ga.out.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ga.out"
	@echo "... game"
	@echo "... genetic"
	@echo "... helpers"
	@echo "... game/body_part.o"
	@echo "... game/body_part.i"
	@echo "... game/body_part.s"
	@echo "... game/food.o"
	@echo "... game/food.i"
	@echo "... game/food.s"
	@echo "... game/gui.o"
	@echo "... game/gui.i"
	@echo "... game/gui.s"
	@echo "... game/player.o"
	@echo "... game/player.i"
	@echo "... game/player.s"
	@echo "... genetic/chromosome.o"
	@echo "... genetic/chromosome.i"
	@echo "... genetic/chromosome.s"
	@echo "... genetic/gene.o"
	@echo "... genetic/gene.i"
	@echo "... genetic/gene.s"
	@echo "... genetic/population.o"
	@echo "... genetic/population.i"
	@echo "... genetic/population.s"
	@echo "... helpers/utils.o"
	@echo "... helpers/utils.i"
	@echo "... helpers/utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

