name: CMake Build and test

on:
  push:
    branches: [ "*" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare ubuntu
      run: python -m pip install -r requirements.txt 

    - name: Run script to Build and Test
      run: |
        chmod +x ./auto-run.sh && ./auto-run.sh
